{% set name = "leptonica" %}
{% set version = "1.78.0" %}
{% set sha256 = "f8ac4d93cc76b524c2c81d27850bfc342e68b91368aa7a1f7d69e34ce13adbb4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DanBloomberg/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches: c74e712799890a600814d4d4970f8f03be254b0a.patch # fixes openjpeg

build:
  number: 0
  skip: True  # [win]
  run_exports:
    - {{ pin_subpackage("leptonica", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - automake
    - libtool
    - m4
    - pkg-config
  host:
    - libwebp
    - zlib
    - libpng
    - libtiff
    - jpeg
    - openjpeg
    - xz
    - giflib
  run:
    - libwebp
    - zlib
    - libpng
    - libtiff
    - jpeg
    - openjpeg
    - xz
    - giflib

test:
  commands:
    - convertfilestopdf --help 2>&1 | grep 'resolution' &> /dev/null
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://github.com/DanBloomberg/leptonica
  license: BSD 2-Clause
  license_family: BSD
  license_file: leptonica-license.txt
  summary: 'Useful for image processing and image analysis applications'
  description: |
    Leptonica is a pedagogically-oriented open source site containing
    software that is broadly useful for image processing and image
    analysis applications.
  doc_url: http://www.leptonica.org/
  dev_url: https://github.com/DanBloomberg/leptonica

extra:
  recipe-maintainers:
    - CurtLH
