{% set version = "1.87.0" %}

package:
  name: leptonica
  version: {{ version }}

source:
  url: https://github.com/DanBloomberg/leptonica/releases/download/{{ version }}/leptonica-{{ version }}.tar.gz
  sha256: c73363397f96eb1295602bf44d708a994ad42046c791bf03ea0505d829bdb6a7
  patches:
    - patches/0001-point-to-our-own-prefix-in-CMake-metadata-on-windows.patch  # [win]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("leptonica", max_pin='x.x') }}

# TODO: conda-forge giflib missing headers on windows?

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - autoconf  # [not win]
    - automake  # [not win]
    - make  # [not win]
    - libtool  # [not win]
    - m4  # [not win]
    - pkg-config  # [not win]
    - cmake  # [win]
  host:
    - giflib
    - libjpeg-turbo
    - libpng
    - libtiff
    - libwebp
    - openjpeg
    - liblzma-devel
    - zlib

test:
  requires:
    # cmake needs a compiler to run package detection
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
  files:
    - cmake_test/
  commands:
    - convertfilestopdf --help 2>&1 | grep 'resolution' &> /dev/null  # [not win]
    # we don't actually have CMake metadata on unix, due to building with autotools;
    # test that CMake+pkgconfig works though
    - cd cmake_test
    - cmake -GNinja -DCMAKE_CXX_STANDARD=17 $CMAKE_ARGS .   # [unix]
    - cmake -GNinja -DCMAKE_CXX_STANDARD=17 %CMAKE_ARGS% .  # [win]

about:
  home: https://github.com/DanBloomberg/leptonica
  license: BSD-2-Clause
  license_family: BSD
  license_file: leptonica-license.txt
  summary: Useful for image processing and image analysis applications
  description: |
    Leptonica is a pedagogically-oriented open source site containing	
    software that is broadly useful for image processing and image	
    analysis applications.
  doc_url: http://www.leptonica.org/
  dev_url: https://github.com/DanBloomberg/leptonica

extra:
  recipe-maintainers:
    - CurtLH
    - izahn
    - chrisdeutsch
