{% set version = "1.86.0" %}

package:
  name: leptonica
  version: {{ version }}

source:
  url: https://github.com/DanBloomberg/leptonica/releases/download/{{ version }}/leptonica-{{ version }}.tar.gz
  sha256: 1fa08e40bb37fd45802d5e6e7b43927449a5c47d4608ef99d3bd3f0fa76baedc
  patches:
    - patches/0001-point-to-our-own-prefix-in-CMake-metadata-on-windows.patch  # [win]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("leptonica", max_pin='x.x') }}

# TODO: conda-forge giflib missing headers on windows?

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - autoconf  # [not win]
    - automake  # [not win]
    - make  # [not win]
    - libtool  # [not win]
    - m4  # [not win]
    - pkg-config  # [not win]
    - cmake  # [win]
  host:
    - giflib
    - libjpeg-turbo
    - libpng
    - libtiff
    - libwebp
    - openjpeg
    - liblzma-devel
    - zlib

test:
  commands:
    - convertfilestopdf --help 2>&1 | grep 'resolution' &> /dev/null  # [not win]

about:
  home: https://github.com/DanBloomberg/leptonica
  license: BSD-2-Clause
  license_family: BSD
  license_file: leptonica-license.txt
  summary: Useful for image processing and image analysis applications
  description: |
    Leptonica is a pedagogically-oriented open source site containing	
    software that is broadly useful for image processing and image	
    analysis applications.
  doc_url: http://www.leptonica.org/
  dev_url: https://github.com/DanBloomberg/leptonica

extra:
  recipe-maintainers:
    - CurtLH
    - izahn
    - chrisdeutsch
