{% set name = "leptonica" %}
{% set version = "1.82.0" %}
{% set sha256 = "155302ee914668c27b6fe3ca9ff2da63b245f6d62f3061c8f27563774b8ae2d6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/DanBloomberg/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - cmake.patch  # [win]

build:
  number: 3
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

# TODO: conda-forge giflib missing headers on windows?

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf  # [not win]
    - automake  # [not win]
    - make  # [not win]
    - libtool  # [not win]
    - m4  # [not win]
    - pkg-config  # [not win]
    - cmake  # [win]
    # latest build of 7.71.1 (build 6) is broken
    - curl <7.71.1  # [win]
    - m2-unzip  # [win]
  host:
    - giflib  # [not win]
    - libjpeg-turbo
    - libpng
    - libtiff
    - libwebp
    - openjpeg
    - xz
    - zlib
  run:
    # libwebp doesn't have run_exports yet (on version in conda-forge-pinning)
    - libwebp

test:
  commands:
    - convertfilestopdf --help 2>&1 | grep 'resolution' &> /dev/null  # [not win]

about:
  home: https://github.com/DanBloomberg/leptonica
  license: BSD-2-Clause
  license_family: BSD
  license_file: leptonica-license.txt
  summary: Useful for image processing and image analysis applications
  description: |
    Leptonica is a pedagogically-oriented open source site containing	
    software that is broadly useful for image processing and image	
    analysis applications.
  doc_url: http://www.leptonica.org/
  dev_url: https://github.com/DanBloomberg/leptonica

extra:
  recipe-maintainers:
    - CurtLH
    - izahn
